# Generated by Django 5.2.4

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='failure_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway_response',
            field=models.TextField(blank=True, help_text='Raw gateway response'),
        ),
        migrations.AddField(
            model_name='payment',
            name='pi_amount',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Amount in Pi', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='pi_exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Pi to USD rate', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='pi_txid',
            field=models.CharField(blank=True, help_text='Pi blockchain transaction ID', max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('paypal', 'PayPal'), ('mpesa', 'M-Pesa'), ('pi_coin', 'Pi Coin'), ('bank_transfer', 'Bank Transfer'), ('crypto', 'Cryptocurrency')], max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pi_payment_id',
            field=models.CharField(blank=True, help_text='Pi Network payment ID', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pi_status',
            field=models.CharField(blank=True, help_text='Pi payment status', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pi_wallet_address',
            field=models.CharField(blank=True, help_text='Pi wallet address', max_length=200),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='PiCoinRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pi_to_usd', models.DecimalField(decimal_places=6, help_text='Pi to USD exchange rate', max_digits=10)),
                ('source', models.CharField(help_text="Rate source (e.g., 'manual', 'api')", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PiPaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pi_payment_id', models.CharField(max_length=100, unique=True)),
                ('amount_pi', models.DecimalField(decimal_places=7, max_digits=15)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('from_address', models.CharField(blank=True, max_length=200)),
                ('to_address', models.CharField(blank=True, max_length=200)),
                ('memo', models.TextField(blank=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('network_fee', models.DecimalField(decimal_places=7, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pi_transactions', to='payments.payment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_method', 'status'], name='payments_pa_payment_b0147c_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['pi_payment_id'], name='payments_pa_pi_paym_2c5c4f_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_at'], name='payments_pa_created_2b4c6d_idx'),
        ),
    ]
