# Generated by Django 5.1.4 on 2025-08-08 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_add_pi_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaB2CTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(max_length=255, unique=True)),
                ('originator_conversation_id', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remarks', models.CharField(max_length=255)),
                ('occasion', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('initiated', 'Initiated'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('response_code', models.CharField(blank=True, max_length=10)),
                ('response_description', models.TextField(blank=True)),
                ('transaction_id', models.CharField(blank=True, max_length=255)),
                ('transaction_receipt', models.CharField(blank=True, max_length=255)),
                ('b2c_charges_paid_account_available_funds', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('receiver_party_public_name', models.CharField(blank=True, max_length=255)),
                ('transaction_completed_date_time', models.DateTimeField(blank=True, null=True)),
                ('b2c_utility_account_available_funds', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('b2c_working_account_available_funds', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'M-Pesa B2C Transaction',
                'verbose_name_plural': 'M-Pesa B2C Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MpesaC2BTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_request_id', models.CharField(max_length=255, unique=True)),
                ('merchant_request_id', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account_reference', models.CharField(max_length=255)),
                ('transaction_desc', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('initiated', 'Initiated'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('result_code', models.CharField(blank=True, max_length=10)),
                ('result_desc', models.TextField(blank=True)),
                ('mpesa_receipt_number', models.CharField(blank=True, max_length=255)),
                ('transaction_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'M-Pesa C2B Transaction',
                'verbose_name_plural': 'M-Pesa C2B Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhonePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('send', 'Send Money'), ('receive', 'Receive Money'), ('refund', 'Refund'), ('commission', 'Commission Payment')], max_length=20)),
                ('provider', models.CharField(choices=[('mpesa', 'M-Pesa'), ('airtel', 'Airtel Money'), ('tkash', 'T-Kash')], default='mpesa', max_length=20)),
                ('phone_number', models.CharField(max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=255)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=255)),
                ('receipt_number', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Phone Payment',
                'verbose_name_plural': 'Phone Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_pa_payment_11cbdd_idx',
            old_name='payments_pa_payment_b0147c_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_pa_pi_paym_c19a91_idx',
            old_name='payments_pa_pi_paym_2c5c4f_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_pa_created_b8a300_idx',
            old_name='payments_pa_created_2b4c6d_idx',
        ),
        migrations.AddField(
            model_name='mpesab2ctransaction',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_b2c_transactions', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='mpesac2btransaction',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_c2b_transactions', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='phonepayment',
            name='initiated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='phonepayment',
            name='mpesa_b2c',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.mpesab2ctransaction'),
        ),
        migrations.AddField(
            model_name='phonepayment',
            name='mpesa_c2b',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.mpesac2btransaction'),
        ),
    ]
