# Generated by Django 5.1.4 on 2025-08-08 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_mpesab2ctransaction_mpesac2btransaction_phonepayment_and_more'),
    ]

    operations = [
    ]
