# Generated by Django 5.1.4 on 2025-08-07 18:14

from django.db import migrations
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    Category = apps.get_model('products', 'Category')
    Brand = apps.get_model('products', 'Brand')
    Product = apps.get_model('products', 'Product')
    
    # Populate category slugs
    for category in Category.objects.all():
        if not category.slug:
            base_slug = slugify(category.name)
            slug = base_slug
            counter = 1
            while Category.objects.filter(slug=slug).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            category.slug = slug
            category.save()
    
    # Populate brand slugs
    for brand in Brand.objects.all():
        if not brand.slug:
            base_slug = slugify(brand.name)
            slug = base_slug
            counter = 1
            while Brand.objects.filter(slug=slug).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            brand.slug = slug
            brand.save()
    
    # Populate product slugs
    for product in Product.objects.all():
        if not product.slug:
            base_slug = slugify(product.name)
            slug = base_slug
            counter = 1
            while Product.objects.filter(slug=slug).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            product.slug = slug
            product.save()


def reverse_populate_slugs(apps, schema_editor):
    # We can't reverse this operation, so we'll just pass
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_options_brand_country_of_origin_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_slugs, reverse_populate_slugs),
    ]
