# Generated by Django 5.2.4 on 2025-08-08 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_currency'),
    ]

    operations = [
    ]
